# Generated by Django 5.1 on 2024-09-02 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2024, 9, 2, 23, 29, 1, 736235)),
        ),
    ]
